# Generated by Django 3.2.4 on 2022-04-24 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=64)),
                ('img_url', models.URLField()),
                ('slug', models.SlugField()),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='flan',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
