# Generated by Django 3.2.4 on 2022-04-24 02:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20220424_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='phoneNumber',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?56?\\d{9}$')]),
        ),
    ]
