# Generated by Django 3.2.4 on 2022-04-24 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_contactform_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
    ]
