# Generated by Django 3.2.4 on 2022-04-24 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_rename_productos_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactform',
            name='phoneNumber',
        ),
    ]
